general:
  eureka:
    server:
      hostname: eureka-server

spring:
  cloud:
    config:
      uri: http://config-server:8888
  rabbitmq:
    host: rabbitmq
  datasource:
    url: jdbc:mysql://mysql:3306/security
